defaults: &defaults
  adapter: postgresql
  encoding: unicode
  min_messages: warning
  timeout: 5000
  pool: 5

development:
  database: moonson_dev
  <<: *defaults

test:
  database: moonson_test
  <<: *defaults
